name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List repository files
        run: ls -R

      - name: List webpage folder contents
        working-directory: ./webpage
        run: ls -R

      - name: Install dependencies
        working-directory: ./webpage
        run: npm install

      - name: Clear cache
        working-directory: ./webpage
        run: npm run clear

      - name: Build Docusaurus site
        working-directory: ./webpage
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Docusaurus_TOKEN }}
          publish_dir: ./webpage/build
